import type { Manifest } from '../types'
import { ZOD_SCHEMA_MARKER } from './extract'

export interface EmitManifestOptions {
  searchRoutes?: Set<string>
  callSearchSources?: Map<string, string>
}

export function emitManifestModule(
  manifest: Manifest,
  options?: EmitManifestOptions,
): string {
  const searchRoutes = options?.searchRoutes ?? new Set<string>()
  const callSearchSources = options?.callSearchSources ?? new Map<string, string>()

  const lines: string[] = [
    '// AUTO-GENERATED by next-file-route — DO NOT EDIT',
    '',
  ]

  const routeSearchExpr = new Map<string, string>()
  const inlineDecls: string[] = []
  let inlineIdx = 0

  for (const routePath of [...searchRoutes].sort()) {
    const src = callSearchSources.get(routePath)
    if (!src) continue
    const varName = `__inline_search_${inlineIdx++}`
    inlineDecls.push(`const ${varName} = ${src};`)
    routeSearchExpr.set(routePath, varName)
  }

  if (inlineDecls.length > 0) {
    lines.push("import { z } from 'zod';", '', ...inlineDecls, '')
  }

  const routesWithoutSearch: Record<string, unknown> = {}
  for (const [path, config] of Object.entries(manifest.routes)) {
    if (config && typeof config === 'object') {
      const { search, ...rest } = config as Record<string, unknown>
      routesWithoutSearch[path] = rest
    } else {
      routesWithoutSearch[path] = config
    }
  }

  lines.push(`const __routesBase = ${JSON.stringify(routesWithoutSearch, null, 2)};`)
  lines.push('')

  if (routeSearchExpr.size > 0) {
    for (const [routePath, expr] of routeSearchExpr) {
      const key = JSON.stringify(routePath)
      lines.push(`if (__routesBase[${key}]) __routesBase[${key}].search = ${expr};`)
    }
    lines.push('')
  }

  lines.push('export const __routes = __routesBase;')
  lines.push('')
  lines.push(`export const __layouts = ${JSON.stringify(manifest.layouts, null, 2)};`)
  lines.push('')

  if (routeSearchExpr.size > 0) {
    lines.push('export const __searchSchemas = {')
    for (const [routePath, expr] of routeSearchExpr) {
      lines.push(`  ${JSON.stringify(routePath)}: ${expr},`)
    }
    lines.push('};')
  } else {
    lines.push('export const __searchSchemas = {};')
  }
  lines.push('')

  lines.push(emitMatchRouteFn(Object.keys(manifest.routes)))

  return lines.join('\n')
}

export function emitRouteTypes(
  routeToFile: Map<string, string>,
  routeValues?: Record<string, unknown>,
): string {
  const lines: string[] = [
    '// AUTO-GENERATED by next-file-route — DO NOT EDIT',
    "declare module 'next-file-route' {",
    '  interface RouteMap {',
  ]

  for (const routePath of [...routeToFile.keys()].sort()) {
    const value = routeValues?.[routePath]
    const typeLiteral =
      value !== undefined && typeof value === 'object' && value !== null
        ? jsonToTypeLiteral(value, 4)
        : 'Record<string, unknown>'
    lines.push(`    ${JSON.stringify(routePath)}: ${typeLiteral}`)
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('export {}')

  return lines.join('\n')
}

function jsonToTypeLiteral(value: unknown, indent: number): string {
  if (value === null) return 'null'
  if (typeof value === 'string') {
    if (value === ZOD_SCHEMA_MARKER) return 'unknown'
    return JSON.stringify(value)
  }
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) return 'number'
    return String(value)
  }
  if (typeof value === 'boolean') return String(value)
  if (Array.isArray(value)) {
    if (value.length === 0) return 'readonly unknown[]'
    const items = value.map((v) => jsonToTypeLiteral(v, indent))
    return `readonly [${items.join(', ')}]`
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value).filter(([, v]) => v !== undefined)
    if (entries.length === 0) return 'Record<string, unknown>'
    const inner = ' '.repeat(indent + 2)
    const close = ' '.repeat(indent)
    const lines = entries.map(([k, v]) => {
      const key = /^[a-zA-Z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)
      return `${inner}readonly ${key}: ${jsonToTypeLiteral(v, indent + 2)};`
    })
    return `{\n${lines.join('\n')}\n${close}}`
  }
  return 'unknown'
}

function emitMatchRouteFn(routePaths: string[]): string {
  return `
export function __matchRoute(pathname) {
  const routes = ${JSON.stringify(routePaths)};
  if (routes.includes(pathname)) return pathname;

  const pathSegments = pathname.split('/').filter(Boolean);
  const isDyn = (s) => s.startsWith('[') && s.endsWith(']');
  const candidates = [];

  for (const pattern of routes) {
    const patternSegments = pattern.split('/').filter(Boolean);

    const optIdx = patternSegments.findIndex((s) => s.startsWith('[[...') && s.endsWith(']]'));
    if (optIdx !== -1) {
      const staticPart = patternSegments.slice(0, optIdx);
      const matches = staticPart.length <= pathSegments.length &&
        staticPart.every((s, i) => isDyn(s) || s === pathSegments[i]);
      if (matches) candidates.push({ pattern, specificity: optIdx, tier: 0 });
      continue;
    }

    const catchAllIdx = patternSegments.findIndex((s) => s.startsWith('[...'));
    if (catchAllIdx !== -1) {
      const staticPart = patternSegments.slice(0, catchAllIdx);
      const matches = pathSegments.length >= catchAllIdx + 1 &&
        staticPart.every((s, i) => isDyn(s) || s === pathSegments[i]);
      if (matches) candidates.push({ pattern, specificity: catchAllIdx, tier: 1 });
      continue;
    }

    if (patternSegments.length !== pathSegments.length) continue;

    let match = true;
    let specificity = 0;
    for (let i = 0; i < patternSegments.length; i++) {
      const seg = patternSegments[i];
      if (isDyn(seg)) {
        // dynamic segments contribute 0 specificity
      } else if (seg === pathSegments[i]) {
        specificity++;
      } else {
        match = false;
        break;
      }
    }
    if (match) candidates.push({ pattern, specificity, tier: 2 });
  }

  if (candidates.length === 0) return null;
  candidates.sort((a, b) => a.tier !== b.tier ? b.tier - a.tier : b.specificity - a.specificity);
  return candidates[0].pattern;
}
`.trim()
}
